version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    links:
      - db
    depends_on:
      db:
        condition: service_started

    environment:
      PGADMIN_DEFAULT_EMAIL: elias@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
