version: "3"
services:
  app:
    build:
      dockerfile: appDockerfile
    ports:
      - 80:80
    links:
      - redis
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:alpine
    
